# Plot the APD90 of the drug simulated by the ORd-SD model and the ORd-CS model
# Plot also the Hill curve of the drug generated by different protocols
import os
import pandas as pd
import sys

import modelling

# Define drug and protocol
drug = sys.argv[1]
protocol_name = 'Milnes'

# Define directory to save figure and load results
fig_dir = '../../figures/supp_mat/model_comparison/'
if not os.path.isdir(fig_dir):
    os.makedirs(fig_dir)

data_dir = '../../simulation_data/model_comparison/' + drug + '/' + \
    protocol_name + '/'

# Set up structure of figure
fig = modelling.figures.FigureStructure(figsize=(9, 3),
                                        gridspec=(1, 2),
                                        wspace=0.3,
                                        plot_in_subgrid=True)
plot = modelling.figures.FigurePlot()

subgridspecs = [(1, 1)] * 2
subgs = []
for i in range(2):
    subgs.append(fig.gs[i].subgridspec(*subgridspecs[i]))
axs = [[[fig.fig.add_subplot(subgs[k][i, j]) for j in range(
    subgridspecs[k][1])] for i in range(subgridspecs[k][0])] for
    k in range(len(subgs))]

# Left panel
# Plot the APD90 of the ORd-SD model and the ORd-CS model for a given drug
panel5 = axs[0]

# Load the APD90 computed by the two models
APD_trapping = pd.read_csv(data_dir + 'SD_APD_pulses2.csv')
APD_conductance = pd.read_csv(data_dir + 'CS_APD_pulses2.csv')

# Organise data for plotting and identify EAD-like behaviour
drug_conc = APD_trapping['drug concentration'].values.tolist()
APD_trapping = [max(APD_trapping.loc[i].values.tolist()[1:-1]) for i in
                range(APD_trapping.shape[0])]
APD_conductance = [max(APD_conductance.loc[i].values.tolist()[1:-1])
                   for i in range(APD_conductance.shape[0])]
EAD_marker = [1050 if (i >= 1000 or j >= 1000) else None for (i, j)
              in zip(APD_trapping, APD_conductance)]

# Plot APD90 of both models
panel5[0][0].plot(drug_conc, APD_trapping, 'o', color='orange',
                  label='ORd-SD model')
panel5[0][0].plot(drug_conc, APD_conductance, '^', color='blue',
                  label='ORd-CS model', alpha=0.8)
panel5[0][0].scatter(drug_conc, EAD_marker, marker=(5, 2), color='k',
                     label='EAD-like AP')

# Adjust figure details
panel5[0][0].set_xscale("log", nonpositive='clip')
panel5[0][0].set_xlabel('Drug concentration (nM)')
panel5[0][0].set_ylabel(r'APD$_{90}$ (ms)')
panel5[0][0].legend(handlelength=1)

# Right panel
# Hill curves of the drug under different protocol stimulation of the SD model
panel6 = axs[1]

# Set up Hill equation and protocols
Hill_model = modelling.HillsModel()
protocol_list = modelling.ProtocolParameters().protocols
line_pattern = ['solid', 'dashed', 'dotted', 'dashdot']
color = ['orange', 'blue', 'red', 'green']

# Load Hill curve coefficients
Hill_coef_df = pd.read_csv(data_dir + '../Hill_curves.csv')

# Define range of drug concentration
drug_conc_lib = modelling.DrugConcentrations()
conc_grid = drug_conc_lib.drug_concentrations[drug]['fine']

# Simulate and plot the Hill curve
for p, prot in enumerate(protocol_list):
    Hill_eq = Hill_coef_df.loc[
        Hill_coef_df['protocol'] == prot]
    Hill_eq = Hill_eq.values.tolist()[0][1:-1]

    panel6[0][0].plot(conc_grid, Hill_model.simulate(
        Hill_eq, conc_grid), linestyle=line_pattern[p], color=color[p],
        label=prot)

# Adjust figure details
panel6[0][0].set_xscale("log", nonpositive='clip')
panel6[0][0].set_xlabel('Drug concentration (nM)')
panel6[0][0].set_ylabel('Normalised\npeak current')
panel6[0][0].legend(handlelength=3)

# Add panel labels
fig.fig.text(0.075, 0.88, '(A)', fontsize=11)
fig.fig.text(0.5, 0.88, '(B)', fontsize=11)

# Save figure
fig.savefig(fig_dir + drug + '_APD_Hill.pdf')
